### PR TITLE
Refactor resource

### PR DESCRIPTION
**Pull request by ionphractal**
The PR contains the following:
* Fix a jq error when services parameter is empty
* Add TLS auth for docker host: this can be used in conjunction with kekru/docker-remote-api-tls image to secure the docker daemon (see also https://gist.github.com/kekru/4e6d49b4290a4eebc7b597c07eaf61f2)
* Refactor Dockerfile to be based on the official docker/compose image, which is lighter as it is based on Alpine
* Refine output of the resource to contain the SHA256 sum of the docker-compose.yml: in my case the file is different from build to build because the image is updated.

### CODE REVIEW

**Review by troykinsella — APPROVED** [review]
This is great. Thanks for the contribution!

**Comment by troykinsella** [comment]
If you get that failing check fixed up, I'll test and merge.

**Comment by ionphractal** [comment]
@troykinsella Err nice. If I'm not logged in, the "Details" link just directs me to hub.docker.com, if I am, I get a 500 *except* if I change the
`https://cloud.docker.com/redirect/?resource_uri=/api/audit/v1/action/2c36abda-651a-473c-b0f6-799ac9c00720/`
into
`https://cloud.docker.com/api/audit/v1/action/2c36abda-651a-473c-b0f6-799ac9c00720/`... so I first thought I had no access to it. Should be fixed...

**Comment by ionphractal** [comment]
? What next... now I get an empty page with 401 in the network debugger.

**Comment by ionphractal** [comment]
Ok I got this, need to build the image manually to see the errors. Strange this isn't already breaking in my pipeline where I used this. Will fix it.

**Comment by troykinsella** [comment]
Looks like the `ci/dockercloud` check is passing, so I'm going to merge this to `develop` and do some further testing before cutting a release. Nice work. Thank you!

**Pull request merged**
